apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Agenda_Python_Django
  annotations:
    github.com/project-slug: AnaCandida/Agenda_Python_Django
    annotations:
    backstage.io/techdocs-ref: value
spec:
  type: website
  lifecycle: development
  owner: guests
